In [1]:
import numpy as np

In [2]:
#numpy array
arr = np.array([1,2,3])
print("Love", arr)

Love [1 2 3]


In [3]:
#creating 2-d array
arr = np.array([[1,2],[2,1]])
print(arr.shape)

(2, 2)


In [4]:
arr = np.array([[[1,2,3,4,5],[3,4,5,6,7],[7,8,9.00,1.345534,4],[2.,4,3,5,6]],[[1,2,3,4,5],[3,4,5,6,7],[7,8,9.00,1.345534,4],[2.,4,3,5,6]]])
print(arr.ndim)

3


In [5]:
arr.shape

(2, 4, 5)

In [6]:
#indexing multidimensional
b = np.array([[0,1],[2,3],[4,5]])
b[1][1]

3

In [7]:
arr

array([[[1.      , 2.      , 3.      , 4.      , 5.      ],
        [3.      , 4.      , 5.      , 6.      , 7.      ],
        [7.      , 8.      , 9.      , 1.345534, 4.      ],
        [2.      , 4.      , 3.      , 5.      , 6.      ]],

       [[1.      , 2.      , 3.      , 4.      , 5.      ],
        [3.      , 4.      , 5.      , 6.      , 7.      ],
        [7.      , 8.      , 9.      , 1.345534, 4.      ],
        [2.      , 4.      , 3.      , 5.      , 6.      ]]])

In [8]:
#creating ndim array
c = np.array([[[2,3,4],[4,5,6],[7,8,9]],[[1,2,3],[2,3,4],[0,8,9]]])
c.ndim

3

In [9]:
c[1][2][0]

0

In [10]:
c

array([[[2, 3, 4],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [2, 3, 4],
        [0, 8, 9]]])

In [11]:
#changing the value of some number in matrix
c[1][2][0] = 25
c

array([[[ 2,  3,  4],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 1,  2,  3],
        [ 2,  3,  4],
        [25,  8,  9]]])

In [12]:
#mentioning array along with it's datatype
np.array([0,4,4], dtype=complex)

array([0.+0.j, 4.+0.j, 4.+0.j])

In [13]:
#for random valuesin matrix 
np.empty([3,3])

array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 6.52e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [14]:
#creating an np arr with all zeros (dtype is genrally in float)
x = np.zeros([2,2,3],dtype=int)
x.shape

(2, 2, 3)

In [15]:
x

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [16]:
#creating an np arr with all ones (dtype is genrally in float)
x = np.ones([2,2,3],dtype=int)
x

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [17]:
#creating list with given range
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [18]:
#generate a sequence starting with 2 of width 0.5 and excluding 6
np.arange(2,6,.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [19]:
#a useful way of creating a sequence with given length
np.linspace(2,6,5)

array([2., 3., 4., 5., 6.])

In [20]:
#a useful way of creating a sequence with given length and with specified number of rows and columns
np.linspace(2,10,20).reshape(4,5)

array([[ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053],
       [ 4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368],
       [ 6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684],
       [ 8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ]])

In [21]:
#retstep finds the difference between the numbers
np.linspace(2,5,5, retstep = True)

(array([2.  , 2.75, 3.5 , 4.25, 5.  ]), 0.75)

In [22]:
np.linspace(0, 200, 100, retstep = True)

(array([  0.        ,   2.02020202,   4.04040404,   6.06060606,
          8.08080808,  10.1010101 ,  12.12121212,  14.14141414,
         16.16161616,  18.18181818,  20.2020202 ,  22.22222222,
         24.24242424,  26.26262626,  28.28282828,  30.3030303 ,
         32.32323232,  34.34343434,  36.36363636,  38.38383838,
         40.4040404 ,  42.42424242,  44.44444444,  46.46464646,
         48.48484848,  50.50505051,  52.52525253,  54.54545455,
         56.56565657,  58.58585859,  60.60606061,  62.62626263,
         64.64646465,  66.66666667,  68.68686869,  70.70707071,
         72.72727273,  74.74747475,  76.76767677,  78.78787879,
         80.80808081,  82.82828283,  84.84848485,  86.86868687,
         88.88888889,  90.90909091,  92.92929293,  94.94949495,
         96.96969697,  98.98989899, 101.01010101, 103.03030303,
        105.05050505, 107.07070707, 109.09090909, 111.11111111,
        113.13131313, 115.15151515, 117.17171717, 119.19191919,
        121.21212121, 123.23232323, 125.

In [23]:
#omits the final point in sequence as for np.arange
np.linspace(2, 4, 5, endpoint = False, retstep = True)

(array([2. , 2.4, 2.8, 3.2, 3.6]), 0.4)

In [24]:
#initialize array from function
def f(i, j):
    return 3*i*j
np.fromfunction(f,(4,3))

array([[ 0.,  0.,  0.],
       [ 0.,  3.,  6.],
       [ 0.,  6., 12.],
       [ 0.,  9., 18.]])

In [25]:
#initialize function directly using lambda
np.fromfunction(lambda i,j: 3*i*j, (4,3), dtype=int)

array([[ 0,  0,  0],
       [ 0,  3,  6],
       [ 0,  6, 12],
       [ 0,  9, 18]])

In [26]:
#creating a "comb" of values in array of length n for which every nth element is 1 but with zeros in all other places
N, n = 20, 5
def f(i):
    return (i%n == 0)*i
comb = np.fromfunction(f,(N,), dtype=int)
comb

array([ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0, 10,  0,  0,  0,  0, 15,  0,
        0,  0,  0])

In [27]:
#attributes for introspection
a = np.array(((1, 0, 3), (1, 1, 1), (2, 0, 4), (4, 0, 2)))
a.shape

(4, 3)

In [28]:
a.ndim #number of dimensions, ndim == len ofshape

2

In [29]:
a = np.array([[[2,0], [3, 8]], [[3,6], [4,5]], [[7, 8], [1, 2]]])
a.shape #depth*length*breadth

(3, 2, 2)

In [30]:
a.ndim

3

In [31]:
a.size #total number of elements

12

In [32]:
a.dtype #data type

dtype('int32')

In [33]:
a.data #buffer in memory containing actual elements

In [34]:
a.itemsize #size in bytes of each element

4

In [35]:
x = np.linspace(1, 5, 5)
x

array([1., 2., 3., 4., 5.])

In [36]:
x**3 #power 3

array([  1.,   8.,  27.,  64., 125.])

In [37]:
x - 1

array([0., 1., 2., 3., 4.])

In [38]:
np.sqrt(x - 1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [39]:
y = np.exp(-np.linspace(0, 2, 5))
y

array([1.        , 0.60653066, 0.36787944, 0.22313016, 0.13533528])

In [40]:
np.sin(x-y)

array([ 0.        ,  0.98431873,  0.48771645, -0.59340065, -0.98842844])

In [41]:
#matrix multiplication in numpy
a = np.array(((1, 2), (2, 1)))
b = np.array(((1, 1), (1, 1)))
a*b


array([[1, 2],
       [2, 1]])

In [42]:
b = a.T
b

array([[1, 2],
       [2, 1]])

In [43]:
np.matmul(a,b)

array([[5, 4],
       [4, 5]])

In [44]:
a.dot(b) #dot product

array([[5, 4],
       [4, 5]])

In [45]:
np.dot(a, b)

array([[5, 4],
       [4, 5]])

In [46]:
a@b

array([[5, 4],
       [4, 5]])

In [47]:
a = np.array([[1, 2, 3], [1, 0, 1]])
b = np.array([1, 2])
np.dot(b, a)

array([3, 2, 5])

In [48]:
a>1

array([[False,  True,  True],
       [False, False, False]])

In [49]:
a<10

array([[ True,  True,  True],
       [ True,  True,  True]])

In [50]:
#np.nan - not a number e.g. 0/0
#np.inf - represents infinity

In [51]:
N = 5
msquare = np.zeros((N, N), dtype = int)
msquare

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [52]:
#magic square - sum of all rows or columns or diagonal from a specific element is the same
N = 5
msquare = np.zeros((N, N), dtype = int)
msquare
n = 1
i, j = 0, N//2

while n <= N**2:
    msquare[i, j] = n
    n += 1
    newi, newj = (i-1)%N, (j+1)%N
    if msquare[newi, newj]:
        i += 1
    else:
        i, j = newi, newj

msquare
        


array([[17, 24,  1,  8, 15],
       [23,  5,  7, 14, 16],
       [ 4,  6, 13, 20, 22],
       [10, 12, 19, 21,  3],
       [11, 18, 25,  2,  9]])

In [53]:
m = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
n = m.flatten() #create independent, flatten copy of m
m

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [54]:
n

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
n[3] = 0
n

array([1, 2, 3, 0, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
m

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [57]:
n

array([1, 2, 3, 0, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
m

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [59]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
c= a.ravel()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
o = m.ravel() #matrix into a single line
o

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
o[3] = 0
o

array([1, 2, 3, 0, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
m

array([[[1, 2, 3],
        [0, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [64]:
e = np.linspace(1, 8, 8)
e

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [65]:
e.resize(2, 4)
e

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [66]:
f = e.reshape(4, 2)
f

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [67]:
f[0, 0] = -99
f

array([[-99.,   2.],
       [  3.,   4.],
       [  5.,   6.],
       [  7.,   8.]])

In [68]:
e

array([[-99.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.]])

In [69]:
#transposing arrays
import numpy as np
a = np.linspace(1, 16, 16)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16.])

In [70]:
a = a.reshape(2, 2, 4)
a

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

In [71]:
a.T

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]])

In [72]:
a.transpose()

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]])

In [73]:
a.transpose().shape

(4, 2, 2)

In [74]:
a.T.shape

(4, 2, 2)

In [75]:
b = np.array([100, 101, 102, 103])
b

array([100, 101, 102, 103])

In [76]:
b.T

array([100, 101, 102, 103])

# Merging and Splitting arrays

In [77]:
#np.vstack - stack arrays vertically(in sequential rows)
#np.hstack - stack arrays horizontally(in sequential columns)
#np.dstack - stack arrays depthwise(along third axis)
#vice-versa happens with "split"

In [78]:
a = np.array([0, 0, 0, 0])
b = np.array([1, 1, 1, 1])
c = np.array([2, 2, 2, 2])
d = np.dstack((a, b, c))
d

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [79]:
d.ndim

3

In [80]:
d1 = np.vstack((a, b, c))
d1

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [81]:
d1.shape

(3, 4)

In [82]:
d2 = np.hstack((a, b, c))
d2

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

In [83]:
d2.shape

(12,)

In [84]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [85]:
m = np.array([[[1, 2, 3], [2, 3, 4]], [[4, 5,6], [7, 8, 9]]])
m

array([[[1, 2, 3],
        [2, 3, 4]],

       [[4, 5, 6],
        [7, 8, 9]]])

In [86]:
n = np.hsplit(m, 2)
n

[array([[[1, 2, 3]],
 
        [[4, 5, 6]]]),
 array([[[2, 3, 4]],
 
        [[7, 8, 9]]])]

# Indexing and Slicing

In [87]:
a = np.linspace(10, 16, 6)
a

array([10. , 11.2, 12.4, 13.6, 14.8, 16. ])

In [88]:
a[1:5:2]

array([11.2, 13.6])

In [89]:
a[2::2]

array([12.4, 14.8])

In [90]:
a[2::-2]

array([12.4, 10. ])

In [91]:
a = np.linspace(1, 12, 12).reshape(4,3)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [92]:
a[1:,1:2] #middle rows, second column onwards

array([[ 5.],
       [ 8.],
       [11.]])

In [93]:
a[3, 1, ...] 

array(11.)

In [94]:
a[:,1] = 0 #set all elements in second column to zero
a

array([[ 1.,  0.,  3.],
       [ 4.,  0.,  6.],
       [ 7.,  0.,  9.],
       [10.,  0., 12.]])

In [95]:
#advanced indexing

In [96]:
import numpy as np
a = np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [97]:
ia = [1,4,5]
a[ia]

array([2., 5., 6.])

In [98]:
ia = np.array(((5,5), (9,1), (0,2)))
a[ia]  #an array to be formed from specified indexes

array([[ 6.,  6.],
       [10.,  2.],
       [ 1.,  3.]])

In [99]:
a = np.linspace(1, 5, 6)
a

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [100]:
a.reshape(2,3)

array([[1. , 1.8, 2.6],
       [3.4, 4.2, 5. ]])

In [101]:
ia = np.array(((1,1), (1,0)))
ja = np.array(((1,2), (2,1)))
a[ia,ja]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
a=np.linspace(1,6,6).reshape(2,3)
a

In [ ]:
a.shape

In [ ]:
b=a[::, np.newaxis]
b  #a new axis is added

In [ ]:
b.shape

# Meshes

In [ ]:
np.linspace(0,5,6)
np.linspace(0,3,4)
X,Y = np.meshgrid(x,y)
X

In [ ]:
Y

In [ ]:
X,Y = np.meshgrid(x,y, sparse = True)
X, Y